version: "3.7"
services:
  web:
    build: app
    ports:
      - 80:80
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: example_123
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-18.04
